apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/custom-metrics-apiserver-simulator.zsm.io_custommetrics.yaml
- bases/custom-metrics-apiserver-simulator.zsm.io_externalmetrics.yaml
